#!/bin/bash
cd ../spl
echo OSSTARTUP COMPILING ...
./spl spl_progs/os_startup.spl
echo TIMER INTERRUPT COMPILING ...
./spl spl_progs/timer_interrupt.spl
echo INT10 COMPILING ...
./spl spl_progs/int10.spl
echo BOOTMODULE COMPILING ...
./spl spl_progs/bootmodule.spl
echo MOD5 COMPILING ...
./spl spl_progs/mod5.spl
echo MOD0 COMPILING ...
./spl spl_progs/mod0.spl
echo MOD4 COMPILING ...
./spl spl_progs/mod4.spl
cd ../xfs-interface
./xfs-interface fdisk
./xfs-interface run ../commands/current.txt